---
abstract: 'Compare two html structures and show differences if it is not same'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-HTML-Differences
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  HTML::Entities: 0
  HTML::Parser: 0
  Test::Differences: 0.5
  Test::Differences::Color: 0
  Text::Diff: 0
  Text::Diff::Table: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Test-HTML-Differences.git
version: 0.03
